name: Self Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # PHP GitHub Action created by https://github.com/nanasess
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '8.2'
    - run: |
        cd Self-Test
        php ./index.php