name: Self Test & Examples

on:
  push:
    branches:
      - 'main'
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['5.6', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run Self-Test
        run: cd Self-Test && php index.php

      - name: Run First-Test Example
        run: cd First-Test && php index.php

      - name: Run Kata Example
        run: cd Kata && php index.php

      - name: Run tempo Example
        run: cd tempo && php index.php

      - name: Run Test-Driven Example
        run: cd Test-Driven && php index.php

      - name: Run Xml-Output Example
        run: cd Xml-Output && php index.php
